#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# Original Cookbooks
cookbook 'base',
  :path => 'site-cookbooks/base'

cookbook 'example_users',
  :path => 'site-cookbooks/example_users'

cookbook 'web',
  :path => 'site-cookbooks/web'

cookbook 'vagrant_extras',
  :git => 'https://github.com/jeremiahsnapp/chef-vagrant_extras'
#  :path => '../cookbooks/vagrant_extras'

cookbook 'byobu',
  :git => 'https://github.com/jeremiahsnapp/chef-byobu'
#  :path => '../cookbooks/byobu'

cookbook 'etckeeper',
  :git => 'https://github.com/jeremiahsnapp/chef-etckeeper'
#  :path => '../cookbooks/etckeeper'

cookbook 'unattended_upgrades',
  :git => 'https://github.com/jeremiahsnapp/chef-unattended_upgrades'
#  :path => '../cookbooks/unattended_upgrades'

# Modified Opscode Maintained Cookbooks
cookbook 'postfix',
  :git => 'https://github.com/jeremiahsnapp/postfix'
#  :path => '../cookbooks/postfix'

cookbook 'logwatch',
  :git => 'https://github.com/jeremiahsnapp/logwatch'
#  :path => '../cookbooks/logwatch'

cookbook 'users',
  :git => 'https://github.com/jeremiahsnapp/users'
#  :path => '../cookbooks/users'

# Community Cookbooks
cookbook 'timezone'

# Opscode Maintained Cookbooks
cookbook 'chef-server'
cookbook 'chef-client'
cookbook 'apt'
cookbook 'git'
cookbook 'openssh'
cookbook 'ntp'
cookbook 'vim'
cookbook 'sudo'

cookbook 'rvm',
  :git => 'https://github.com/fnichol/chef-rvm', ref: 'v0.8.6'

## Monitoring
cookbook 'sensu'
cookbook 'collectd',
  :git => 'https://github.com/coderanger/chef-collectd'
cookbook 'collectd_plugins',
  :git => 'https://github.com/coderanger/chef-collectd_plugins'
cookbook 'graphite',
  :git => 'https://github.com/heavywater/chef-graphite'
cookbook 'gdash',
  :git => 'https://github.com/heavywater/chef-gdash'

## Logging
# cookbook 'logstash',
#   :git => 'https://github.com/heavywater/chef-logstash'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
