#
# Cookbook Name:: base
# Recipe:: default
#
# Copyright 2012, Jeremiah Snapp
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# tree is a very helpful command to have
package "tree"

# add timestamps to bash history logs
cookbook_file "/etc/profile.d/histtimeformat.sh" do
  source "histtimeformat.sh"
  owner  "root"
  group  "root"
  mode   "0644"
  action :create
end

# install our CA root certificate for the example.edu domain
# TLS_CACERT in /etc/ldap/ldap.conf will be able to see this certificate so
# ldap clients will be able to verify TLS/SSL connections to our servers that use
# certificates generated by our CA root server
cookbook_file "/usr/local/share/ca-certificates/example-ca.pem" do
  source   "example-ca.pem"
  owner    "root"
  group    "root"
  mode     "0644"
  action   :create
  notifies :run, "execute[update-ca-certificates]"
end

execute "update-ca-certificates" do
  command "update-ca-certificates"
  action  :nothing
end

# Make sure btmp and wtmp files exist so login attempt information will get stored for 'last' and 'lastb' commands
# A quote from the end of 'man last' "they can be created with a simple touch(1) command (for example, touch /var/log/wtmp)."

file "/var/log/btmp" do
  owner "root"
  group "root"
  mode  "0644"
  action :create_if_missing
end

file "/var/log/wtmp" do
  owner "root"
  group "root"
  mode  "0644"
  action :create_if_missing
end
